version: '3'

services:
  postgres:
    image: postgres
    container_name: nest-postgres-container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data
    restart: always
    networks:
      - nestapp

  app:
    build: .
    container_name: nest-api-container
    entrypoint: sh -c "dockerize -wait tcp://postgres:5432 -timeout 30s npm start"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    networks:
      - nestapp
    depends_on:
      - postgres

networks:
  nestapp:
    driver: bridge